In [13]:
import pandas
import joblib

In [4]:
dataset=pandas.read_csv('SalaryData.csv')

In [5]:
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [6]:
y=dataset['Salary']

In [8]:
type(y)

pandas.core.series.Series

In [10]:
x=dataset['YearsExperience'].values.reshape(30,1)

In [11]:
type(x)

numpy.ndarray

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model= LinearRegression()

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test=  train_test_split(x, y, test_size=0.20, random_state=42)

In [19]:
X_train

array([[9.6],
       [4.9],
       [8.2],
       [5.3],
       [3.2],
       [3.7]])

In [22]:
y_train

28    122391.0
24    109431.0
12     56957.0
0      39343.0
4      39891.0
16     66029.0
5      56642.0
13     57081.0
11     55794.0
22    101302.0
1      46205.0
2      37731.0
25    105582.0
3      43525.0
21     98273.0
26    116969.0
18     81363.0
29    121872.0
20     91738.0
7      54445.0
10     63218.0
14     61111.0
19     93940.0
6      60150.0
Name: Salary, dtype: float64

In [23]:
X_train.shape

(24, 1)

In [24]:
X_test.shape

(6, 1)

In [25]:
model.fit(X_test, y_test)

LinearRegression()

In [26]:
model.coef_

array([9328.30086858])

In [27]:
y_pred = model.predict(X_test)

In [28]:
y_pred

array([118476.57161947,  74633.55753713, 105416.95040345,  78364.87788457,
        58775.44606054,  63439.59649483])

In [29]:
c = model.intercept_

In [30]:
c

28924.883281081347

In [32]:
joblib.dump(model , 'salary.pk1')

['salary.pk1']